### ISSUE TITLE
Akinator.continue doesn't works

### ISSUE THREAD

**Issue by Ethan459** [jgoralcz/aki-api#151]
*My Code:
```ts
import { Aki } from 'aki-api'
;(async (): Promise<void> => {
    const aki = new Aki({ region: 'en', childMode: true })
    await aki.start()
    console.log(aki)
    await aki.step(0)
    console.log(aki)
    await aki.step(1)
    await aki.win()
    console.log(aki)
    await aki.continue()
})()
```
*Error:
```
C:\Wee\node_modules\aki-api\dist\src\functions\Request.js:82
    if (!result || result.completion != 'OK' || !(checkParamProperty in result.parameters)) {
                                                                     ^

TypeError: Cannot use 'in' operator to search for 'answers' in undefined
    at request (C:\Wee\node_modules\aki-api\dist\src\functions\Request.js:82:70)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Akinator.continue (C:\Wee\node_modules\aki-api\dist\src\Akinator.js:99:24)
    at async a (C:\Wee\dist\test.js:28:5)
```

**Comment by therealharpaljadeja** [comment]
Yes, doesn't work for me too

**Comment by therealharpaljadeja** [comment]
you need to add this

https://github.com/therealharpaljadeja/akinator-farcaster-frame/blob/2f59ca3e49922fd2e06b53ecf651102182af24b9/Akinator.ts#L192
