### ISSUE TITLE
Error: Could not find a server matching the region en

### ISSUE THREAD

**Issue by hobavi** [jgoralcz/aki-api#155]
Akinator has started giving an error when attempting to get the server.
Easily reproducible by running the example code:
```
const { Aki } = require('aki-api');

const run = async () => {
    const region = 'en';
    const childMode = false;
    const proxy = undefined;

    const aki = new Aki({ region, childMode, proxy });
    await aki.start();
    console.log('question:', aki.question);
    console.log('answers: ', aki.answers);
};

run().catch(console.error);
```

> Error: Could not find a server matching the region en
>     at Akinator.start (./node_modules/aki-api/dist/src/Akinator.js:49:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async run (./index.js:9:5)

**Comment by kitekun** [comment]
Same bro

**Comment by azul372** [comment]
Same. Has anyone solved this?

**Comment by Salientekill** [comment]
I'm facing the same problem, any solution?

**Comment by PrincessCaity0321** [comment]
Yes, same problem.

**Comment by gcamerator** [comment]
Same

**Comment by lindionez** [comment]
Same thing here (Region PT)

**Comment by BannerBomb** [comment]
Bump

**Comment by BannerBomb** [comment]
Confirmed to be fixed in commit https://github.com/jgoralcz/aki-api/commit/167f05794437951d6e74dfdfab5a3142a3622e56
